variables:
  DOCKER_DRIVER: overlay2
  DOCKERHUB_REPO_PREFIX: ixdotai
  DOCKERHUB_REPO_NAME: cioban

stages:
  - lint
  - build
  - release

.tags-template: &tags-definition
  tags:
    - ix-ai

.build-template: &build-definition
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"},\"index.docker.io\":{\"auth\":\"${DOCKERHUB_REGISTRY_AUTH}\"}}}" > /kaniko/.docker/config.json
    - echo "/kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile ${DESTINATION}"
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile ${DESTINATION}

shellcheck:
  <<: *tags-definition
  image: pipelinecomponents/shellcheck:latest
  stage: lint
  script:
    - find . -name .git -type d -prune -o -type f  -name \*.sh -print0 | xargs -0 -P $(nproc) -r -n1 shellcheck

build:dev:
  <<: *tags-definition
  <<: *build-definition
  only:
    - master
  before_script:
    - export DESTINATION="--destination ${CI_REGISTRY_IMAGE}:dev-${CI_COMMIT_REF_NAME} --destination=index.docker.io/${DOCKERHUB_REPO_PREFIX}/${DOCKERHUB_REPO_NAME}:dev-${CI_COMMIT_REF_NAME}"

publish:release:
  <<: *tags-definition
  <<: *build-definition
  stage: release
  only:
    - tags
  before_script:
    - export DESTINATION="--destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    - export DESTINATION="${DESTINATION} --destination ${CI_REGISTRY_IMAGE}:latest"
    - export DESTINATION="${DESTINATION} --destination=index.docker.io/${DOCKERHUB_REPO_PREFIX}/${DOCKERHUB_REPO_NAME}:${CI_COMMIT_REF_NAME}"
    - export DESTINATION="${DESTINATION} --destination=index.docker.io/${DOCKERHUB_REPO_PREFIX}/${DOCKERHUB_REPO_NAME}:latest"

publish:readme:
  <<: *tags-definition
  stage: release
  variables:
    README_PATH: ${CI_PROJECT_DIR}/README.md
  only:
    - master
  image:
    name: sheogorath/readme-to-dockerhub:latest
    entrypoint: ['']
  script:
    - node /app/index.js
